// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7--tVmabE1tBKJdsmGky6f_hlp00gibA',
    appId: '1:995628426264:web:fac1553629a8d6e4eecf6d',
    messagingSenderId: '995628426264',
    projectId: 'assignment-9d163',
    authDomain: 'assignment-9d163.firebaseapp.com',
    storageBucket: 'assignment-9d163.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0CgRZivfDC0RarVLJgZ_dLjz43FMnZbc',
    appId: '1:995628426264:android:e2cbf221877fa211eecf6d',
    messagingSenderId: '995628426264',
    projectId: 'assignment-9d163',
    storageBucket: 'assignment-9d163.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYwon4k3Uc_egMlv1R5c9A3M2dTk5Y1DI',
    appId: '1:995628426264:ios:7cc8b6a075be1febeecf6d',
    messagingSenderId: '995628426264',
    projectId: 'assignment-9d163',
    storageBucket: 'assignment-9d163.appspot.com',
    iosBundleId: 'com.example.assignment',
  );
}
